from __future__ import annotations

from aws_cdk import (
    RemovalPolicy,
    aws_s3 as s3,
)
from constructs import Construct


class BucketsConstruct(Construct):
    """Provision S3 buckets used by the system.

    Creates three buckets:
    - events_bucket: stores structured events (JSON/logs) from the pipeline
    - images_bucket: stores snapshot images captured by the video agent
    - audio_bucket: stores audio files generated by the system
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        bucket_name_prefix: str,
    ) -> None:
        super().__init__(scope, construct_id)

        events_bucket_name = f"{bucket_name_prefix}-events"
        images_bucket_name = f"{bucket_name_prefix}-images"
        audio_bucket_name = f"{bucket_name_prefix}-audio"

        self.events_bucket = s3.Bucket(
            self,
            "EventsBucket",
            bucket_name=events_bucket_name,
            enforce_ssl=True,
            versioned=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        self.images_bucket = s3.Bucket(
            self,
            "ImagesBucket",
            bucket_name=images_bucket_name,
            enforce_ssl=True,
            versioned=False,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )
        
        self.audio_bucket = s3.Bucket(
            self,
            "AudioBucket",
            bucket_name=audio_bucket_name,
            enforce_ssl=True,
            versioned=False,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        self.events_bucket_name_output = events_bucket_name
        self.images_bucket_name_output = images_bucket_name 
        self.audio_bucket_name_output = audio_bucket_name